// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsersCrud.DAL;

#nullable disable

namespace UsersCrud.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231006230626_AddUsersData")]
    partial class AddUsersData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");

                    b.HasData(
                        new
                        {
                            RolesId = new Guid("2dc2c800-6e33-470d-87e6-f7dfcfdebc09"),
                            UsersId = new Guid("4cdbb269-bc5a-4d68-85d9-381d8b667df6")
                        },
                        new
                        {
                            RolesId = new Guid("2dc2c800-6e33-470d-87e6-f7dfcfdebc09"),
                            UsersId = new Guid("d9ebeb68-e7d5-4430-8866-a23660c1a4e2")
                        },
                        new
                        {
                            RolesId = new Guid("76695450-ea70-4398-891d-bf1cdfa0d7e4"),
                            UsersId = new Guid("86c1e29a-b899-449d-ac08-7cd798850cd2")
                        },
                        new
                        {
                            RolesId = new Guid("aef1452f-f830-4c51-91d1-372209eb83d8"),
                            UsersId = new Guid("ebe53741-14e6-4cf3-9797-6e3dae227d49")
                        },
                        new
                        {
                            RolesId = new Guid("513c041c-bfaa-498d-9433-d66411f24370"),
                            UsersId = new Guid("3d52299a-3ccc-4e11-95a3-c5fd845977ae")
                        },
                        new
                        {
                            RolesId = new Guid("aef1452f-f830-4c51-91d1-372209eb83d8"),
                            UsersId = new Guid("3d52299a-3ccc-4e11-95a3-c5fd845977ae")
                        });
                });

            modelBuilder.Entity("UsersCrud.DAL.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2dc2c800-6e33-470d-87e6-f7dfcfdebc09"),
                            Name = 0
                        },
                        new
                        {
                            Id = new Guid("76695450-ea70-4398-891d-bf1cdfa0d7e4"),
                            Name = 1
                        },
                        new
                        {
                            Id = new Guid("aef1452f-f830-4c51-91d1-372209eb83d8"),
                            Name = 2
                        },
                        new
                        {
                            Id = new Guid("513c041c-bfaa-498d-9433-d66411f24370"),
                            Name = 3
                        });
                });

            modelBuilder.Entity("UsersCrud.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cdbb269-bc5a-4d68-85d9-381d8b667df6"),
                            Age = 20,
                            Email = "user1@email.com",
                            Name = "User 1"
                        },
                        new
                        {
                            Id = new Guid("d9ebeb68-e7d5-4430-8866-a23660c1a4e2"),
                            Age = 36,
                            Email = "user2@email.com",
                            Name = "User 2"
                        },
                        new
                        {
                            Id = new Guid("86c1e29a-b899-449d-ac08-7cd798850cd2"),
                            Age = 30,
                            Email = "admin@email.com",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("ebe53741-14e6-4cf3-9797-6e3dae227d49"),
                            Age = 33,
                            Email = "support@email.com",
                            Name = "Suport"
                        },
                        new
                        {
                            Id = new Guid("3d52299a-3ccc-4e11-95a3-c5fd845977ae"),
                            Age = 35,
                            Email = "super.admin@email.com",
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("UsersCrud.DAL.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UsersCrud.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
